### ISSUE TITLE
Firefox crashes when download reaches 99%

### ISSUE THREAD

**Issue by fullmetal1** [dnsev-h/eze#10]
Seems to happen every time for certain galleries. Seems to be bigger galleries

https://exhentai.org/g/550559/ea0ba4c906/
https://exhentai.org/g/727651/c225b6cf0d/

Two examples for which firefox crashes

**Comment by dnsev-h** [comment]
It may be an issue with your Firefox, maybe being out of date or any extensions you may have installed. I tested both links and they don't crash for me.

Beyond that, it's likely that it's a Firefox bug that I'm unable to reproduce. Maybe provide some info on what version of Firefox you're using and any other extensions you might have? Also, the download settings you use. I can't guarantee that will help, but it's worth a shot.

**Comment by fullmetal1** [comment]
The issue seems to only persist in Nightly (I'm currently on 51.0a). When I tried Firefox 48.0 the download worked. I don't know if this is a temporary issue of Nightlys, or if some change is going to be passed on to Firefox in the coming months to break your script

**Comment by dnsev-h** [comment]
Well, looks like you were right, this issue did propagate into Firefox 49. As expected of Mozilla.

Anyways, I attempted a workaround in the code in 1.0.8.2, and it seems to be more stable for me, though I can't be 100% positive.

If you continue to experience this error, let me know and I may look further into it.

**Comment by fullmetal1** [comment]
Sasuga mozilla. I'll be sure to let you know

**Comment by fullmetal1** [comment]
Well the galleries are downloading now and I haven't had any issues

**Comment by dnsev-h** [comment]
Good to hear. I've tested a bit too without error. It's a pretty stupid issue which was causing the bug, and one I couldn't easily reproduce with a standalone script. Maybe it had something to do with using Greasemonkey as well, who knows.
