### ISSUE TITLE
Removed gallery info recovery not working anymore

### ISSUE THREAD

**Issue by DumbIdiot** [dnsev-h/eze#14]
Removed galleries just shows the normal "This gallery has been removed or is unavailable." textbox instead of showing the gallery info. The script still keeps the page from redirecting to the homepage though.

**Comment by tallos** [comment]
Really hope this gets fixed, its the primary reason I use eze.

**Comment by dnsev-h** [comment]
For testing:
https://exhentai.org/g/484736/3f8dfaa4ba

**Comment by dnsev-h** [comment]
Fixed in [1.0.8.6](https://github.com/dnsev-h/eze/commit/e18af5045c6a1eee1e807c81071d7c2695335b85).

Problem occurred due to the removed gallery message being changed.
