### ISSUE TITLE
Full title readability on search results

### ISSUE THREAD

**Issue by InstallShieldWizard** [dnsev-h/eze#2]
![eze](https://cloud.githubusercontent.com/assets/6142538/6431265/48510cda-c065-11e4-83b1-ca3b91de6d14.png)

I also use E-H Highlighter and this is how it looks like if it's active with eze. Is it possible to have an option to remove the stroke?

**Comment by dnsev-h** [comment]
Title emphasis should be disabled for EHH modified entries in [1.0.3.4](https://github.com/dnsev-h/eze/commit/1b8102eaab1764390caebc6bff0c35ef1ec4192f)
