### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by aaaplus1** [dnsev-h/eze#21]
e-h had a setting update
https://forums.e-hentai.org/index.php?showtopic=213374

For eze:
Settings page and front page link is broken.

Front Page button forces "?f_sdesc=on&f_sdt1=on&f_sdt2=on&f_storr=on&f_sr=on&f_srdd=2&f_sh=on&f_apply=Apply+Filter" regardless of site settings.

eze-settings page is inaccessible, redirects to e-h settings page.

**Comment by zer0shikiseihai** [comment]
The eze 1.0.8.8 fixed the settings page for me, but my front page is still being redirected to "?f_sr=on&f_srdd=3&f_sh=on&f_apply=Apply+Filter" without any of the category settings (doujinshi, manga, etc.)

**Comment by dnsev-h** [comment]
Should be fixed in 1.0.8.9 now, though I had to add checkboxes on the settings page for the categories you want enabled. This used to be automatically generated from the user config cookie, but since that no longer stores settings, it cannot be used.

**Comment by zer0shikiseihai** [comment]
Works perfectly! Thanks dnsev-h.
